### ISSUE TITLE
 Error: dom-to-image is required since 0.7.2

### ISSUE THREAD

**Issue by ScorprocS** [hizzgdev/jsmind#529]
Hello I'm using jsmind in an angular application. It was working well utill 0.7.2 version.

I'have this issue in the console
```
node_modules\jsmind\es6\jsmind.screenshot.js:8 Uncaught Error: dom-to-image is required
    at node_modules\jsmind\es6\jsmind.screenshot.js:8:444
    at node_modules\jsmind\es6\jsmind.screenshot.js:8:16
    at node_modules\jsmind\es6\jsmind.screenshot.js:8:265
```

So I have tried to import it in the project 
npm i dom-to-image
and I've added the script in angular.json
```
   "scripts": [
              "./node_modules/jsmind/es6/jsmind.js",
              "./node_modules/jsmind/es6/jsmind.draggable-node.js",
              "./node_modules/jsmind/es6/jsmind.screenshot.js",
              "./node_modules/dom-to-image/dist/dom-to-image.min.js"
            ],
            
```
But I still have the issue. Do you have any idea how to solve this ? Thanks

**Comment by ScorprocS** [comment]
My bad I just had to insert               "./node_modules/dom-to-image/dist/dom-to-image.min.js" on the first position in the array.
It's working now
